---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pg-article
  name: pg-article
  namespace: pg
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pg-article
  template:
    metadata:
      labels:
        run: pg-article
    spec:
      containers:
        - image: ${IMAGE}
          name: pg-article-pod
