---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pg-auth
  name: pg-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pg-auth
  template:
    metadata:
      labels:
        run: pg-auth
    spec:
      containers:
        - image: "registry.cn-shenzhen.aliyuncs.com/pg/auth:2023-08-10-13-40-05"
          name: pg-auth-pod
---
apiVersion: v1
kind: Service
metadata:
  name: pg-auth-service
  labels:
    test: test
    labele2: label
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    run: pg-auth
  sessionAffinity: None
  type: ClusterIP