---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pg-apigw
  name: pg-apigw
  namespace: pg
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pg-apigw
  template:
    metadata:
      labels:
        run: pg-apigw
    spec:
      containers:
        - image: ${IMAGE}
          name: pg-apigw-pod
