server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    dsn_master: root:password@tcp(ssh.2pg.cn:30139)/auth
    dsn_slave: ["root:password@tcp(ssh.2pg.cn:30139)/auth"]
    max_idle_connection: 10
    max_open_connection: 10
    connection_max_lifetime: 360s
    log_level: info
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    keeplive: 20s
    pool_size: 10
